apiVersion: acme.com/v1
kind: Workload
metadata:
  name: vote-casting-app
  namespace: acme-operators
image: kind-registry:5001/vote-casting-app:latest
route: /vote
replicas: 1
port: 5173
env: 
  VITE_SERVER_URL: http://localhost
  VITE_SERVER_PORT: "80"
command: ["npm", "run", "dev"]